# Generated by Django 4.2.18 on 2025-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_report_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('url', 'URL'), ('ip', 'IP'), ('domain', 'Domain'), ('hash', 'Hash')], max_length=10),
        ),
    ]
